### ISSUE TITLE
What is the motivation behind using "intensity"?

### ISSUE THREAD

**Issue by wiseman** [shriphani/Listener#1]
The original Moattar-Homayounpour algorithm doesn't seem to use frame "intensity" as you do--did you add it, and why?

**Comment by shriphani** [comment]
Initially I wanted it to capture loud noises in the background in addition to speech. Hence the magic 45 dB number.

**Comment by wiseman** [comment]
Thanks!

(Seems like you could just use a straight intensity threshold, in that case.)
